### ISSUE TITLE
I cant see the app in the zway store (v2.3.4) , even after using your token. Should i install manually ?

### ISSUE THREAD

**Issue by kiwiamg** [pathec/ZWay-OpenHABConnector#2]

**Comment by rolo2130** [comment]
I had this issue as well. Have you tried the token provided in the installation instructions? I'm not in front of my machine at the moment, but I think there is an option to show beta apps in the store.

**Comment by rolo2130** [comment]
I had this issue as well. Have you tried the token provided in the installation instructions? I'm not in front of my machine at the moment, but I think there is an option to show beta apps in the store.

Disregard, small screen, didn't notice your full title. Looks like you tried the token.

**Comment by pathec** [comment]
Hi,

Please look at the category selection: All Apps must be selected.

![zwayappstore](https://cloud.githubusercontent.com/assets/9437468/25576329/4cc2cd58-2e5e-11e7-9a50-c942706c416b.png)

**Comment by kiwiamg** [comment]
pathec Thanks thats what I was missing. Connector seems to be working very well. :)
