### ISSUE TITLE
Feature Request: HTTPS support

### ISSUE THREAD

**Issue by syphr42** [pathec/ZWay-OpenHABConnector#4]
Due to the following line, there is no way to specify a secure connection to openHAB:

https://github.com/pathec/ZWay-OpenHABConnector/blob/4ea39229fd4dca4b55f1ee0d0bfb8e0a66454d0a/index.js#L373

Can this be modified so that the protocol, host, and port is specified in one configuration variable or alternatively can there be a toggle added to switch between HTTP and HTTPS?

**Comment by pathec** [comment]
Hi, that makes sense. I'll create an update the next few days.
Best regards Patrick

**Comment by pathec** [comment]
Hi, I made the update in branch [feat/https-support](https://github.com/pathec/ZWay-OpenHABConnector/tree/feat/https-support). Do you have the possibility to install and test before I upload the update to the App Store? I tested it successfully locally

The default value for the protocol is `http`. So the existing configuration should not be broken.

If you edit the configuration in Z-Way, you need to execute the following command to get the module to work properly again: `http://YOUR_IP:8083/ZAutomation/api/v1/devices/OpenHabConnector/command/refreshListener`

Best regards
Patrick

**Comment by syphr42** [comment]
Thanks for the quick response on this. I should be able to test it
tomorrow. I'll report back after.

**Comment by mtzro2003** [comment]
Sorry for hi-jacking the thread... 
But I want to ask @pathec if he is still maintaining the ZWay binding for openHAB.
There are numerous reports about problems with ZWay binding and openHAB >= 2.2 on the [forum](https://community.openhab.org/t/new-z-way-binding/14096) and Patrick never responded once in the last months.
So, Patrick, are you still interested in this project? There are no hard feelings if you have dropped the project, it's understandable, but would be great to know for sure 😄

**Comment by syphr42** [comment]
I tested the update and it works - great job!

I did see a minor problem with uppercase vs. lowercase on the protocol, so I opened PR #5. 

Thanks again for putting this together so quickly! Much appreciated.

**Comment by pathec** [comment]
Ok. I upload the new version 0.1.8 to the App Store.
